import { type NextPage } from "next";
import { useRouter } from 'next/router'
import Head from "next/head";
import { useEffect, useState } from "react";
import { useDispatch, useSelector } from 'react-redux';
import { Deck, type Flashcard } from "../../utils/commonTypes";
import FlashcardJSX from "../../components/FlashcardJSX";
import Header from "../../components/Header";
import { selectCurrentDeck, selectCurrentUser, selectFlashcards, updateCurrentDeck, updateCurrentFlashcards } from "../../slices/appSlice";
import { getAPI, sampleDeck } from "../../utils/assets";
import axios from "axios";

const DeckPage: NextPage = () => {
  const router = useRouter();
  const { id } = router.query; 
  // get deck by id 
  const [index, setIndex] = useState<number>(0); 
  const user = useSelector(selectCurrentUser);
  const deck = useSelector(selectCurrentDeck);
  const flashcards = useSelector(selectFlashcards); 
  const [total, setTotal] = useState<number>(flashcards.length); 
  const dispatch = useDispatch();

  useEffect(() => {
    // make new deck 
    if (!id) return; 
    axios.get(getAPI(window) + `/decks/${id}`).then((res) => {
      const deckObj: Deck = res.data.data; 
      console.log(deckObj);
      dispatch(updateCurrentDeck(deckObj));
      dispatch(updateCurrentFlashcards(deckObj.flashcardIds));
    }); 
  }, [id])

  useEffect(() => {
    if (flashcards.length === 0) {
      dispatch(updateCurrentFlashcards(sampleDeck));
    } 
    setTotal(flashcards.length);
    setIndex(flashcards.length === 0 ? -1 : 0); 
  }, [flashcards]); 

  const addFlashcard = async () => {
    const index = flashcards.length; 
    const body: any = {
      deckId: deck._id, 
      question: `Question ${index}`, 
      answer: `Answer ${index}`, 
      userId: user._id
    }
    const res: any = await axios.post(getAPI(window) + `/flashcards`, body); 
    const flashcard: Flashcard = res.data.data; 
    const newFlashcards = [...flashcards, flashcard]; 
    dispatch(updateCurrentFlashcards(newFlashcards)); 
    setTotal(total+1); 
    setIndex(index); 
  }

  const prev = () => {
    if (index > 0) {
      setIndex(index - 1); 
    }
  }

  const next = () => {
    if (index < flashcards.length - 1) {
      setIndex(index + 1); 
    }
  }

  return (
    <>
      <Head>
        <title>Deck</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <Header /> 
        <div className="items-center justify-center">
          <div className="container flex items-center justify-center gap-12 px-16 py-4 text-white">
            { index+1 } / { total }
          </div>

          <div className="container flex items-center justify-center gap-12 px-16 py-4 ">
            {flashcards && flashcards.length ? (
              <FlashcardJSX flashcard={flashcards[index]} />
            ) : null}
          </div>

          <div className="container flex items-center justify-center gap-12 px-16 py-16">
            <div 
              className="flex max-w-xl flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              onClick={prev}
            >
              <h1 className='text-white'> prev </h1>
            </div>
            <div 
              className="flex max-w-xl flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              onClick={addFlashcard}
            >
              <h3 className="text-2xl font-bold">New flashcard +</h3>
            </div>
            <div 
              className="flex max-w-xl flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              onClick={next}
            >
              <h1 className='text-white'> next </h1>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default DeckPage;
